# Generated by Django 5.0.6 on 2024-08-08 10:04

import dj_app.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('id_tk', models.CharField(blank=True, null=True)),
                ('chap_ngay', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emoj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('tl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quyen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quyen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopTruyenDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('truyen_ids', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_tk', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('gioi_tinh', models.CharField(blank=True, max_length=10, null=True)),
                ('noi_sinh', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='truyen_images/')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='tai_khoan_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='tai_khoan_permissions', to='auth.permission')),
                ('id_quyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tai_khoans', to='dj_app.quyen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('nhac', models.TextField(blank=True, null=True)),
                ('id_tk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luans', to=settings.AUTH_USER_MODEL)),
                ('id_chap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binh_luans', to='dj_app.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Truyen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(null=True)),
                ('tinh_trang', models.CharField(max_length=50)),
                ('gioi_thieu', models.TextField()),
                ('tac_gia', models.TextField()),
                ('ten_khac', models.TextField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='truyen_images/')),
                ('img_url', models.TextField(blank=True, null=True)),
                ('id_tk', models.CharField(blank=True, null=True)),
                ('Limit', models.BooleanField(default=False)),
                ('nametl', models.ManyToManyField(related_name='truyens', to='dj_app.theloai')),
            ],
        ),
        migrations.CreateModel(
            name='TheoDoi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tk', models.CharField(blank=True, max_length=255, null=True)),
                ('tinhtrang', models.BooleanField(default=False)),
                ('id_truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theo_dois', to='dj_app.truyen')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='truyen_images/')),
                ('img_url', models.TextField(blank=True, null=True)),
                ('id_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='dj_app.chapter')),
                ('id_truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='dj_app.truyen')),
            ],
        ),
        migrations.CreateModel(
            name='LuotXem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tk', models.CharField(blank=True, max_length=255, null=True)),
                ('tinhtrang', models.BooleanField(default=False)),
                ('luotxem_ngay', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=100, null=True)),
                ('id_chap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luot_xems', to='dj_app.chapter')),
                ('id_truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luot_xems', to='dj_app.truyen')),
            ],
        ),
        migrations.CreateModel(
            name='LikeCmt',
            fields=[
                ('id', models.CharField(default=dj_app.models.generate_unique_id, max_length=255, primary_key=True, serialize=False)),
                ('like', models.BooleanField(default=True)),
                ('id_tk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LikeCmts', to=settings.AUTH_USER_MODEL)),
                ('td_cmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LikeCmts', to='dj_app.binhluan')),
                ('id_truyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LikeCmts', to='dj_app.truyen')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tk', models.CharField(blank=True, max_length=255, null=True)),
                ('diem', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('id_truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gias', to='dj_app.truyen')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='id_truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='dj_app.truyen'),
        ),
        migrations.AddField(
            model_name='binhluan',
            name='id_truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luans', to='dj_app.truyen'),
        ),
    ]
