# Generated by Django 5.0.6 on 2024-08-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='dharma_name',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
