# Generated by Django 5.0.6 on 2024-08-14 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0002_taikhoan_dharma_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_type', models.CharField(choices=[('normal', 'Bình Thường'), ('tiendao', 'Tiên Đạo'), ('vodao', 'Võ Đạo'), ('maphap', 'Ma Pháp')], default='normal', max_length=10)),
                ('id_tk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
