# Generated by Django 5.0.6 on 2024-08-16 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0005_taikhoan_level_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuBinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_doc', models.BooleanField(default=False)),
                ('thoi_gian_xem', models.DateTimeField(blank=True, null=True)),
                ('binh_luan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='dj_app.binhluan')),
                ('id_tk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_binh_luans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_tk', 'binh_luan')},
            },
        ),
    ]
