# Generated by Django 5.0.6 on 2024-09-04 04:28

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0007_binhluan_da_doc_delete_lichsubinhluan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='truyen_images/'),
        ),
    ]
