# Generated by Django 5.0.6 on 2024-10-27 16:18

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0008_alter_taikhoan_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='face_data',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='face_data/'),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
