# Generated by Django 5.0.6 on 2024-10-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0009_taikhoan_face_data_taikhoan_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
