# Generated by Django 5.0.6 on 2024-10-30 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0010_taikhoan_is_active_taikhoan_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='id_quyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tai_khoans', to='dj_app.quyen'),
        ),
    ]
