# Generated by Django 5.0.6 on 2024-10-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0011_alter_taikhoan_id_quyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
