# Generated by Django 4.2.16 on 2024-10-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0013_remove_taikhoan_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
