# Generated by Django 4.2.16 on 2024-10-30 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0014_taikhoan_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
