# Generated by Django 4.2.16 on 2024-11-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0018_alter_taikhoan_face_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
