# Generated by Django 4.2.16 on 2024-11-16 10:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0019_alter_taikhoan_face_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='face_data',
            field=models.ImageField(default='truyen_images/default_image.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='truyen_images/'),
        ),
    ]
