version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: QUYNHANH
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/be_dj
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      - DJANGO_SETTINGS_MODULE=be_dj.settings

volumes:
  postgres_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
