# Generated by Django 5.0.6 on 2024-07-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='truyen_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
